### PR TITLE
Sending message

### PR DESCRIPTION
**Pull request by dannylu03**
### **What I've Done:**
- Created the UI for the chat screen using Java Swing
- Implemented sending a message through the UI which persists into the database
- Fixed the getChat method in DBService to return the Chat entity properly

### **What I Have Left to Do:**
- Write unit tests for my functions
- Document my code

### CODE REVIEW

**Review by Dismany0 — APPROVED** [review]
I'm seeing that one of the tests failed, with there being a null pointer exception in one of the gateway related files. Do we have the json key in our github files right now? I don't see any changes that would likely result in the failure.

For the UI portion of this pull request, everything looks fine, assuming that the error is something we are already aware about.

**Review by SlothfulAlfred — APPROVED** [review]
Looks good to me.

**Review by terenceliu88 — APPROVED** [review]
Looks good to me

**Review by muzammil004 — DISMISSED** [review]
Looks great to me!

**Review by alx672219 — DISMISSED** [review]
I do not think there is anything you need to change more. It looks good to me.

**Review by SlothfulAlfred — APPROVED** [review]

**Review by SlothfulAlfred — DISMISSED** [review]

**Review by alx672219 — DISMISSED** [review]
I see how you resolved the merge conflicts. It looks good to me now.

**Review by muzammil004 — APPROVED** [review]
Looks good to me!

**Review by muzammil004 — APPROVED** [review]
Looks good to me!

**Review by erji2022 — APPROVED** [review]
Looks good to me.

**Review by Dismany0 — APPROVED** [review]
conflict fix, approved

**Pull request merged**
