### PR TITLE
Created connection to Firebase NoSQL database and the skeleton

### PR DESCRIPTION
**Pull request by dannylu03**
# Description
- Setup the connection between app with cloud Firebase Database through the addition of the service.json key. 
- DBinitializer class initializes an object reference for use to access the Database.
- DBService class is used to perform operations on the database.

Will be used by the gateway layer in our project.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good to me!

**Comment by alx672219** [comment]
That looks good to me!

**Review by ghost — APPROVED** [review]
I think it looks good to me!

**Review by alfred-mikhael — CHANGES_REQUESTED** [review]
I just have a couple of comments, 
- can we name the documents by user_id instead of username, since there may be more than one user with the same username! Similarly, Main.getUser should take an int 
- The Main class should be renamed (I know you were just using it for testing, you could just create a unit test for it instead)

**Comment by dannylu03** [comment]
Just added the change to fetch by userID, though I don't understand what we would change the Main class to be. Isn't this the main entry class, so Main would be an appropriate  name?

**Comment by SlothfulAlfred** [comment]
What's confusing me is that there are database methods defined in the Main class. I was under the impression that our Main class should just initialize all the objects we need and the JFrame, and not have any other methods inside it. Are you thinking of something different for the Main class?

**Comment by dannylu03** [comment]
> What's confusing me is that there are database methods defined in the Main class. I was under the impression that our Main class should just initialize all the objects we need and the JFrame, and not have any other methods inside it. Are you thinking of something different for the Main class?

Oh I see, what you mean. Yeah the methods were just meant for testing and I was just thinking that after merging we can comment it out for later use.

**Review by Dismany0 — APPROVED** [review]
Are the files in tutorial just for testing? Other than that everything looks fine

**Pull request merged**
