### PR TITLE
Implement Firebase registration system.

### PR DESCRIPTION
**Pull request by SlothfulAlfred**
In this pull request I have:
- Added a method in DBService to get all the user ids that are in the database
- Implemented UserRegistrationGateway with Firebase 
- **Renamed methods in User**: getDefaultLang -> *getDefault_lang* and setDefaultLang -> *setDefault_lang*

I still need to:
- Implement UserLoginGateway with Firebase
- Finish the Login view
- Implement navigation between views

### CODE REVIEW

**Comment by SlothfulAlfred** [comment]
I renamed the methods in User because the Firebase methods in DBService automatically create / store objects using the getter and setter methods. Since getDefaultLang did not match with the field name default_lang, the User objects were not being created / stored properly.

**Review by dannylu03 — COMMENTED** [review]
I was considering if we should split off the main function in the main class into separate functions for certain tasks such as initializing the Jframe would be "JframeInit"

**Comment by SlothfulAlfred** [comment]
You're right, I was actually just using it for testing and committed the file by accident. I will make that change

**Comment by SlothfulAlfred** [comment]
I did as you said and removed the initialization of the JPanels into their own methods. In addition, I have created a navigation system for us to use.

**Review by muzammil004 — DISMISSED** [review]
Looks great to me!

**Review by Dismany0 — APPROVED** [review]
Looks good, are all the views separate windows? or are they all put together in main?

**Review by Dismany0 — APPROVED** [review]
There is a few conflicts between this and main right now. I compared the files and it seems like most of them are updated and should be used instead of what we have on main right now. I'm approving this for now because I think these conflicts are required to be resolved before merging.

**Review by muzammil004 — APPROVED** [review]
The code looks good to me!

**Review by dannylu03 — APPROVED** [review]
Looks good to me!

**Comment by SlothfulAlfred** [comment]
Resolved merge conflicts!

**Review by muzammil004 — APPROVED** [review]
Looks good to me!

**Review by Dismany0 — APPROVED** [review]
Conflicts have been fixed, everything looks fine now

**Review by dannylu03 — APPROVED** [review]
Resolved conflicts looks good to me!

**Pull request merged**
