### PR TITLE
Basic package structure

### PR DESCRIPTION
**Pull request by SlothfulAlfred**
Added the views package and shared package (currently only containing .gitignore so that git realizes they exist) and an entities package with a basic User entity.

### CODE REVIEW

**Review by muzammil004 — DISMISSED** [review]
These look good to me! Maybe consider making the getter and setter methods for User public.

**Comment by SlothfulAlfred** [comment]
Thanks, I did forget to make the methods public. I pushed a new commit to change that. I also noticed an issue in setPassword and changed it with the latest commit.

**Review by muzammil004 — DISMISSED** [review]

**Review by Dismany0 — DISMISSED** [review]
Looks good, once this is merged to main we should put our entities in here too right?

**Review by muzammil004 — DISMISSED** [review]

**Comment by dannylu03** [comment]
Added the Message and Chat entities.

**Review by muzammil004 — COMMENTED** [review]
Would we maybe need a getter method for messages in the Chat entity class? 
Also maybe consider changing the name of the message attribute in the Message class to "text" or "contents".

**Comment by SlothfulAlfred** [comment]
We should also add a constructor for the Chat and Messages classes.

**Comment by dannylu03** [comment]
Thanks, just added the constructors and the getter and setter methods for the Chat entity. 
Check most recent commit.

**Review by muzammil004 — DISMISSED** [review]

**Review by muzammil004 — COMMENTED** [review]
We also talked about including an id attribute for the Message entity, if I'm not mistaken?

**Comment by dannylu03** [comment]
Added the id fields for Message and Chat entity

**Review by muzammil004 — COMMENTED** [review]
I think we should have id as a parameter in the constructor and have a getter and setter for it (for both entities).

**Review by erji2022 — APPROVED** [review]

**Comment by dannylu03** [comment]
Made some changes to the User class and added  changes for Chat and Message class.

**Review by alx672219 — CHANGES_REQUESTED** [review]
Can you add getUser_id , setUser_id, getContacts, and set_contacts

**Comment by alx672219** [comment]
Looks good to me now.

**Review by alx672219 — APPROVED** [review]

**Review by muzammil004 — APPROVED** [review]

**Review by Dismany0 — APPROVED** [review]
My bad my last approve was on the wrong pull req

**Pull request merged**
