### PR TITLE
Updated the file structure, added some test files

### PR DESCRIPTION
**Pull request by Dismany0**
Reorganized the files according to the file structure we have been using:
**Added**:
Data, failure, input and output boundaries, interactor, and gateways for both MessageTranslate and AudioConversion

**Left to do**
Add boundaries and interactors for AudioRecording
Work on user interface
Add Javadocs
Unit Tests

### CODE REVIEW

**Review by SlothfulAlfred — COMMENTED** [review]
You should move `MessageTest.java` into the tests package, otherwise looks good to me.

**Review by dannylu03 — DISMISSED** [review]
Looks good to me

**Review by SlothfulAlfred — APPROVED** [review]
looks good to me

**Review by dannylu03 — DISMISSED** [review]
Looks good to me!

**Review by SlothfulAlfred — COMMENTED** [review]
Tests should not be in the use case package. Otherwise looks good to me!

**Review by SlothfulAlfred — APPROVED** [review]

**Review by SlothfulAlfred — APPROVED** [review]

**Review by erji2022 — APPROVED** [review]

**Review by dannylu03 — APPROVED** [review]
Fixed conflicts, looks good

**Pull request merged**
