### PR TITLE
Skeleton

### PR DESCRIPTION
**Pull request by dannylu03**
# Description
Reference code for using the DBService class and how to access the database can be found in this pull request.
The skeleton for using database from the gateway layer will be merged from this pull request.

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Looks good to me

**Review by ghost — DISMISSED** [review]
It seems good to me :)

**Review by Dismany0 — APPROVED** [review]
I think this is due to my mix up earlier with github I'm seeing a lot of my files in the changes here

**Review by alfred-mikhael — COMMENTED** [review]
For the AudioUseCase package, the name should be audio_use_case in snake case to follow the Java conventions and for the testing framework to work properly.

**Review by mmzml — APPROVED** [review]
After Alfred's suggested changes are implemented, it looks good to me.

**Pull request merged**
