### PR TITLE
Integrating UI

### PR DESCRIPTION
**Pull request by muzammil004**
### What I've done:
- Integrated all the UI together
  - Made a HomeScreen that combines the ContactScreen, ProfileScreen, and ChatScreen
  - Added RecordButton to ChatScreen
  - Made LoginScreen navigate to HomeScreen when user successfully logs in
- Corrected some Clean Architecture in a bunch of classes (ContactScreen, ProfileScreen, etc.)
- Got rid of a lot of warnings
### Left to do:
Nothing

**Functionality is done!**

### CODE REVIEW

**Review by terenceliu88 — DISMISSED** [review]
Looks good to me!

**Review by SlothfulAlfred — DISMISSED** [review]
In `LoginScreen`, `LoginResponse`, and `HomeScreen` there is a direct reference to `User` which violates Clean Architecture. We can probably solve this by using an Observer pattern. I will approve this PR, but I will create an issue so that we can resolve this before the final submission.

**Review by Dismany0 — APPROVED** [review]
Merging UI, demonstrated during our in person meeting
approving

**Review by terenceliu88 — APPROVED** [review]
Looks good to me

**Review by Dismany0 — APPROVED** [review]
Approving after conflicting code fix

**Review by SlothfulAlfred — APPROVED** [review]

**Pull request merged**
