### PR TITLE
Api translate usecase

### PR DESCRIPTION
**Pull request by Dismany0**
I added a translator and speech to text
I have tested the speech to text with English and French and I think it is working fine

### CODE REVIEW

**Review by muzammil004 — DISMISSED** [review]
Looks great to me!

**Review by dannylu03 — APPROVED** [review]
Looks good to me!

**Review by terenceliu88 — DISMISSED** [review]
Looks Good to me

**Review by terenceliu88 — APPROVED** [review]
Looks good to me

**Review by dannylu03 — APPROVED** [review]
Looks good to me

**Review by muzammil004 — COMMENTED** [review]
Looks good to me!

**Review by Dismany0 — COMMENTED** [review]
I fixed up the gradle because the merge request had some duplicate code

**Review by muzammil004 — APPROVED** [review]

**Pull request merged**
