### PR TITLE
Partial Implementation of registration use case

### PR DESCRIPTION
**Pull request by SlothfulAlfred**
So far I have:

- Completed the skeleton for the login and registration use cases by adding presenters, output boundaries, and a class extending RunTimeException. 
- Partially implemented RegisterScreen so that button clicks now do things

What remains to be done: 
- Create and implement LoginScreen 
- Complete implementation of RegisterScreen by accessing database / files
- Navigate between RegisterScreen, LoginScreen and the HomeScreen (and a welcome screen if there is time)
- Add unit tests

### CODE REVIEW

**Review by muzammil004 — COMMENTED** [review]
Most of the code looks good to me! 
My only concern is that I thought the presenters of each use case should be in the use case package instead of the views package. Am I mistaken?

**Comment by SlothfulAlfred** [comment]
I'm thought the actual implementation should be in the views but the interface (RegisterOutputBoundary in this case) should be in the use case package. At least that's what Paul's Clean Architecture example does.

**Comment by muzammil004** [comment]
> I'm thought the actual implementation should be in the views but the interface (RegisterOutputBoundary in this case) should be in the use case package. At least that's what Paul's Clean Architecture example does.

Oh ok. I must be mistaken then. I'll update the package structure for my use case too then.

**Review by muzammil004 — APPROVED** [review]

**Review by erji2022 — APPROVED** [review]

**Review by Dismany0 — APPROVED** [review]
Looks good

**Pull request merged**
