### PR TITLE
Skeleton for user login and registration use case

### PR DESCRIPTION
**Pull request by SlothfulAlfred**
Add the skeleton for the user login and registration use cases. This includes, input boundaries, output boundaries, transient data and response classes, and interactors. Most methods are not implemented yet. I will add the corresponding javadocs and unit tests as I implement the methods.

### CODE REVIEW

**Review by muzammil004 — COMMENTED** [review]
Hey Alfred! Reviewed the code and it looks good for now (since this is just a skeleton). 
I just have one concern: Is there a reason for having to interfaces called RegistrationInputBoundary and UserRegisterInputBoundary? They seem to do the same thing, which is being input boundaries for the user_register_use_case. 
If it was on purpose, could you let me know so I can then approve these changes?

**Comment by SlothfulAlfred** [comment]
You're right that's an oversight on my part. I've added a commit to remove RegistrationInputBoundary. Thanks Muzammil!

**Review by muzammil004 — DISMISSED** [review]

**Review by Dismany0 — APPROVED** [review]
Looks good to me for skeleton classes. I have no idea if my approves are working because I think I am not the first person to approve, but it still only shows 1

**Review by muzammil004 — APPROVED** [review]

**Review by dannylu03 — APPROVED** [review]
Looks good to me

**Pull request merged**
