### PR TITLE
Sending message

### PR DESCRIPTION
**Pull request by dannylu03**
### **What I've Done:**
- Implemented the Send Message end-to-end use case from creating the message to adding it to a chat
- Integrate Send Message with the Database
- Design the UI using Java Swing

### **What I need to Done:**
- Write unit tests for my implementation

### CODE REVIEW

**Comment by dannylu03** [comment]
Don't review the TextMessage class as I am waiting to combine my implementation with AudioMessage before implementing it.

**Review by alx672219 — APPROVED** [review]
Looks good

**Review by terenceliu88 — APPROVED** [review]
Not sure why so many files changed but looks good

**Review by SlothfulAlfred — CHANGES_REQUESTED** [review]
In SendMessageController, you call MessageInputBoundary.createMessage, but this method doesn't exist! You also call MessageOutputBoundary.sendMessage but this method doesn't exist either.

Also, I believe the controller SendMessageController should be in the views package.

**Review by terenceliu88 — CHANGES_REQUESTED** [review]
I believe the controller should take the chatID as a parameter. Additionally, the controller should also be in views.

**Review by alx672219 — APPROVED** [review]
yes I agree with terenceliu88.
Besides it, everything looks good.

**Comment by dannylu03** [comment]
Made some major changes to the DBService file as well as the finishing touches on my backend files. 
Ignore all the commented code, that is for future reference and testing. Just focus on the major business logic files and the gateway.

All I have left to do now is the UI.

**Review by SlothfulAlfred — DISMISSED** [review]
Looks good to me!

**Review by terenceliu88 — DISMISSED** [review]
Looks good

**Review by muzammil004 — COMMENTED** [review]
When you send a message, you should also be updating the messages field of the chat document with the chatID parameter you have. So maybe in DBService, the addMessage method should also take in an int parameter called chatID and use that to update the messages field of that specific chat document in Firebase. And then in SendMessageGateway when you call dbService.addMessage in the sendMessage method, you can just pass in the chatID parameter of sendMessage. Hope this helps!

**Comment by dannylu03** [comment]
> When you send a message, you should also be updating the messages field of the chat document with the chatID parameter you have. So maybe in DBService, the addMessage method should also take in an int parameter called chatID and use that to update the messages field of that specific chat document in Firebase. And then in SendMessageGateway when you call dbService.addMessage in the sendMessage method, you can just pass in the chatID parameter of sendMessage. Hope this helps!

Thanks! Just fixed the issue, if you could take a look now.

**Review by muzammil004 — APPROVED** [review]
Looks good to me!

**Review by alx672219 — DISMISSED** [review]
I see how you fixed the issues now. All the files look good to me. Great Work!

**Review by SlothfulAlfred — DISMISSED** [review]
LGTM

**Review by terenceliu88 — DISMISSED** [review]
Looks good to me!

**Review by SlothfulAlfred — APPROVED** [review]
Looks good to me!

**Review by terenceliu88 — APPROVED** [review]
Looks good!

**Review by alx672219 — APPROVED** [review]
I see what you have fixed. All the files look good to me!

**Pull request merged**
