### PR TITLE
Fix merge conflicts so project compiles.

### PR DESCRIPTION
**Pull request by SlothfulAlfred**

### CODE REVIEW

**Review by Dismany0 — DISMISSED** [review]

**Review by muzammil004 — APPROVED** [review]
The changes look good to me!

**Review by muzammil004 — APPROVED** [review]
The code looks good to me!

**Review by dannylu03 — APPROVED** [review]
Looks good to me!

**Review by Dismany0 — APPROVED** [review]
More merge confclit review fixed

**Pull request merged**
