### PR TITLE
Searching adding deleting contacts

### PR DESCRIPTION
**Pull request by ghost**
What I did:
1. Changed the comments from Korean to English
2. Finished building UI for ContactScreen
3. Connected AddContact to the database

What I left to do:
1. Make some Unit Tests and write Java Doc
2. Since my UI violates Clean Architecture rules which ContactScreen references users DBService, I need to fix this so that   the order of my layers always points inward instead of outward.

### CODE REVIEW

**Review by mmzml — DISMISSED** [review]
Looks good to me!

**Review by ghost — DISMISSED** [review]
Looks good!

**Review by Dismany0 — DISMISSED** [review]
Comment changes, approving

**Review by mmzml — APPROVED** [review]
Looks good to me!

**Review by ghost — APPROVED** [review]
Looks good

**Review by erji2022 — APPROVED** [review]
Looks okay to me.

**Review by alfred-mikhael — CHANGES_REQUESTED** [review]
You should not be referencing `User` or `DBService` from `ContactScreen` since it is in the interface adapters layer. It should only have references to controllers and presenters.

**Pull request merged**
