### PR TITLE
Use case editing & deleting

### PR DESCRIPTION
**Pull request by erji2022**
What I've done:
- Created message_edit_delete_use_case package.
- Implemented classes such as interactor, presenter, controller, gateway, and response model for message editing use case.
- Implemented classes for message deleting use case.
- Add tests for both use cases.

What to do:
- Add java docs.

### CODE REVIEW

**Review by muzammil004 — COMMENTED** [review]
The code for the use case looks good. Two things
1. I think something went wrong and you're adding a folder called "shelf". I think it's ok to remove it.
2. There shouldn't be a .idea folder in src. There should only be on outside src.
Everything else looks good!

**Comment by erji2022** [comment]
> The code for the use case looks good. Two things
> 
> 1. I think something went wrong and you're adding a folder called "shelf". I think it's ok to remove it.
> 2. There shouldn't be a .idea folder in src. There should only be one outside src.
>    Everything else looks good!

Hi!, I have made changes according to your suggestion. I think it's OK to merge now.

**Review by muzammil004 — DISMISSED** [review]
Looks good to me!

**Review by SlothfulAlfred — COMMENTED** [review]
I have a couple of comments about your code:
1. I noticed in `MessageEditInteractor` you did not put `gateway.edit(data)` in a try-catch block, what if the internet cuts out during the request and it throws a run time exception?
2. In `MessageEditFirebaseSystem` you import `DBInitializer` but I don't see any uses for it?

**Review by Dismany0 — APPROVED** [review]

**Review by Dismany0 — APPROVED** [review]
I think I previously reviewed this already, but there mightve been a few small changes. I think the files look fine here. 
Alfred previously left a comment about surrounding the gateway in a try catch in case your internet drops, have you tried testing this? If it ends up being a problem, I think I have parts of my use case that would have the same issue

**Review by muzammil004 — DISMISSED** [review]
Looks good to me!

**Review by Dismany0 — APPROVED** [review]

**Review by dannylu03 — DISMISSED** [review]
Looks good to me!

**Review by SlothfulAlfred — DISMISSED** [review]

**Review by muzammil004 — DISMISSED** [review]
Looks good to me

**Review by Dismany0 — DISMISSED** [review]
Just conflict fixes, approving

**Review by dannylu03 — APPROVED** [review]
Fixed conflicts, looks good

**Review by Dismany0 — APPROVED** [review]
just another merge conflict, approving again

**Review by muzammil004 — APPROVED** [review]
Approved!

**Review by dannylu03 — APPROVED** [review]
Fixed conflicts, looks good

**Pull request merged**
