### PR TITLE
Add documentation for user login and registration use cases and tests.

### PR DESCRIPTION
**Pull request by SlothfulAlfred**
# Description

Add documentation for user login and registration use cases.

# Design Patterns

None

# SOLID Principles

None 

# Breaking Change
- [ ] Check this if your changes will cause merge conflicts in other branches.

# Checklist:
- [x] My code follows Java style conventions
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added Javadocs for new classes and methods
- [x] My changes generate no new relevant warnings
- [x] I have added tests for any new functionality added
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by erji2022 — APPROVED** [review]
Looks fine to me!

**Review by muzammil004 — APPROVED** [review]
Looks good to me!

**Review by alx672219 — APPROVED** [review]
Looks good to me!

**Review by muzammil004 — APPROVED** [review]
Looks good to me!

**Pull request merged**
