### PR TITLE
Sending message

### PR DESCRIPTION
**Pull request by dannylu03**
### **What I've Done:**
- Fixed the architecture for the Send Message use case so that the presenter only talks with the controller. And the hiearchical structure is clear.

This makes it such that the Send Message architecture adheres to clean architecture as the inner layers won't depend on the outer layers.

### **What I have left:**
- Unit tests for the send message functions
- Documentation for Send Message use case

### CODE REVIEW

**Review by mmzml — DISMISSED** [review]
These changes look good to me!

**Review by ghost — DISMISSED** [review]
I see how you have changed ur codes. It looks good to me now.

**Review by alfred-mikhael — CHANGES_REQUESTED** [review]
You have a reference to `DBService` in `ChatScreen` and in `MessageInteractor`. `ChatScreen` should not have a reference to `DBService` at all, only presenters and controllers, while `MessageInteractor` should reference a gateway!

**Comment by dannylu03** [comment]
> You have a reference to `DBService` in `ChatScreen` and in `MessageInteractor`. `ChatScreen` should not have a reference to `DBService` at all, only presenters and controllers, while `MessageInteractor` should reference a gateway!

Nice catch, just made the changes

**Review by mmzml — DISMISSED** [review]
The code looks good to me!

**Review by mmzml — DISMISSED** [review]
Looks good to me!

**Review by alfred-mikhael — CHANGES_REQUESTED** [review]
`ChatScreen` should not have a direct reference to `MessageInteractor` (or `MessageInputBoundary`). The controller should be initialized *outside* of the class and injected into it through the constructor.

**Review by Dismany0 — DISMISSED** [review]
looks good

**Review by ghost — DISMISSED** [review]
Looks good to me

**Review by mmzml — DISMISSED** [review]
Looks good to me!

**Review by ghost — DISMISSED** [review]
Looks good to me!!

**Review by Dismany0 — DISMISSED** [review]

**Review by mmzml — DISMISSED** [review]
Looks good to me!

**Review by Dismany0 — DISMISSED** [review]

**Review by alfred-mikhael — DISMISSED** [review]
Will approve for now so that we can get something running, but note that the constructor in `ChatScreen` has a very long parameter list which is a code smell. I recommend you use a facade object to collect all the controllers. Also, you don't need both the username and the senderID, since they correspond to the same user.

**Review by Dismany0 — APPROVED** [review]

**Review by mmzml — APPROVED** [review]
Looks good to me!

**Review by alfred-mikhael — APPROVED** [review]

**Pull request merged**
