### PR TITLE
Updated 2/3 use cases with documentation

### PR DESCRIPTION
**Pull request by Dismany0**
**What I did:**
Added Javadocs to all the files within the AudioConverter, AudioRecorder use cases

**TODO**
Add javadocs to the MessageTranslator use case
Add unit tests for AudioConverter, AudioRecorder and MessageTranslator use cases
Merge the UI with the main home screen UI

Reorganize where the audio file is stored

### CODE REVIEW

**Comment by Dismany0** [comment]
Don't approve of this PR yet, it is still a work in progress. 

The autograder seems to have failed due to a testing file I don't have on my side for editing messages. So it doesn't seem to be an actual problem

**Review by muzammil004 — APPROVED** [review]
The code looks good to me!

**Review by alx672219 — APPROVED** [review]
I see how you added the documentations. They look good to me now!

**Review by erji2022 — APPROVED** [review]
Looks good to me!

**Pull request merged**
