### PR TITLE
I finished unit tests and java doc

### PR DESCRIPTION
**Pull request by ghost**
# Description

1. I added Java documentation for all layers for Adding Contacts and Deleting Contacts which are

Contact Screen
Controller
Interactor
Gateway
Persistence
DBService

2. I implemented Unit Tests for Add/Delete Contact Data , Add/Delete Contact Response, Add/Delete Contact Interactor, Add/Delete Contact Controller, Add/Delete Contact Firebase System, and Add/Delete Contact Presenter.

# Design Patterns

I just double checked that all the layers for my use cases, the inner layers do not dependent on the outer layers.

# SOLID Principles

None

# Breaking Change

None

# Checklist:
- [x] My code follows Java style conventions
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added Javadocs for new classes and methods
- [x] My changes generate no new relevant warnings
- [x] I have added tests for any new functionality added
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by mmzml — APPROVED** [review]
Looks good to me!

**Review by dannylu03 — APPROVED** [review]
Looks good to me

**Review by erji2022 — APPROVED** [review]
Looks okay to me!

**Review by Dismany0 — APPROVED** [review]
I am unsure if the sourceCompatibility and targetCompatibility will result in errors, but other than that, it looks good.

Approving since other group members seem to say that it will not result in an error.

**Pull request merged**
