### PR TITLE
Created Unit Tests, JavaDocs, and modified some errors

### PR DESCRIPTION
**Pull request by ghost**
# Description

- Created unit tests for the FirebaseSystem, Controller, Data, Interactor, Response, and Presenter Class in the Profile Customization Use Case 

- Created JavaDocs for all the methods in the profile_customization_use_case and also the methods in DBService that Profile Customization uses

Fixes # (issue)

- Changed CustomizationGatewayImplementation to CustomizationFirebaseSystem to match the proper naming convention

- Modified the existName method in DBService so that it correctly checks the newly chosen name instead of userID which was what it was checking before

# Design Patterns

Please mention which - if any - design patterns that you have implemented in this pull request.

# SOLID Principles

Please mention which - if any - SOLID principles you have followed in this pull request.

# Breaking Change
- [ ] Check this if your changes will cause merge conflicts in other branches.

# Checklist:
- [x] My code follows Java style conventions
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added Javadocs for new classes and methods
- [x] My changes generate no new relevant warnings
- [x] I have added tests for any new functionality added
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by alfred-mikhael — DISMISSED** [review]

**Review by mmzml — DISMISSED** [review]
Looks good to me!

**Review by erji2022 — DISMISSED** [review]
Looks good to me!

**Review by Dismany0 — APPROVED** [review]
Fixed Unit Tests

Approved

**Review by ghost — APPROVED** [review]
I see how you fixed your unit tests.
Looks fine to me!

**Review by mmzml — APPROVED** [review]
Your fix on unit tests looks good.

**Pull request merged**
